### ISSUE TITLE
Update SEND Rule Id in schema

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#174] opened 2023-03-24 14:45 UTC
**AC**
Send rule id regex has been updated to SEND\d+(\.\d+)?

**Comment by RamilCDISC** [comment] 2023-05-09 21:37
The acceptance criteria for this issue is fulfilled and the issue is clear from QA review. But I observed yellow lines in one file. The lines can be seen in the screenshot too.

<img width="838" alt="174" src="https://github.com/cdisc-org/conformance-rules-editor/assets/113539111/470baf3a-6f40-4b1e-afae-06d7e09deec7">

**Comment by gerrycampion** [comment] 2023-05-09 21:57
This is an issue with that rule, not with the schema. The Rule with Rule id = SEND2 follows the schema correctly and shows no yellow lines.

**Comment by RamilCDISC** [comment] 2023-07-01 21:37
### Validation Summary:

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. All related rules were checked in the rule editor for the specifics mentioned in the acceptance criteria. The rule editor was run locally against the dev database.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The Tests were run manually by going through the rule body and comparing all of those rule id regexes with this regex: ‘SEND\d+(.\d+)?’

### Results:
After successful running of manual and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.

### Deviations and Non-conformances:
No deviations or non-conformances were observed.

### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.

**Closed** 2023-07-05 15:05 UTC
Labels: schema
