### ISSUE TITLE
Schema updates for FDA rules

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#179] opened 2023-04-11 20:04 UTC
- FDA Standards.References.Version should be changed from "1.5 March 2021" to "1.6"
- Rule Id regex should be moved to Citations.Cited Guidance
- Rule Id regex should be changed to: `(CT|SD|SE)\d^{4}[A-Z]?`
- Add SENDIG-AR 1.0, SENDIG-DART 1.1, SEND 3.1.1
- Add enum for Citations.Document to be [FDA, CDISC]

**Comment by RamilCDISC** [comment] 2023-05-09 21:32
The acceptance criteria for this issue is not fulfilled. The rule id regex has not been moved to citations.citedguidance as required in the second step of AC. You can also see yellow lines were observed in the rule SENDING-AR. 

<img width="1505" alt="179" src="https://github.com/cdisc-org/conformance-rules-editor/assets/113539111/045d990f-4908-468b-be02-c8e4f4f639eb">

**Comment by gerrycampion** [comment] 2023-05-09 21:53
@RamilCDISC this result is expected. The yellow lines are appearing because the rule id regex is checking the value correctly, but the values are blank. This is an issue with that rule, not with the schema.

**Comment by RamilCDISC** [comment] 2023-05-09 21:57
Thank you very much for the confirmation for yellow lines. What about - The rule id regex has not been moved to citations.citedguidance as required in the second step of AC.

**Comment by gerrycampion** [comment] 2023-05-09 22:20
That is why the yellow lines appear when the cited guidance is blank. To see evidence of a correct rule that passes the schema validation of the Cited Guidance value, you can look at SD9999 for example.

**Comment by RamilCDISC** [comment] 2023-05-11 16:52
confirmed with @gerrycampion all the test pass and AC is full-filled

**Comment by RamilCDISC** [comment] 2023-07-02 18:37
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. All related rules were checked in the rule editor for the specifics mentioned in the acceptance criteria. The rule editor was run locally against the dev database.
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:
The Tests were run manually by going through the rule body and verifying the changes related to this issue. At first it was found that the citations.cited guidance was not moved to the place where it should have. But later on explanation by developer @gerrycampion made things clear.
### Results:
After successful running of manual and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression**: The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.

**Closed** 2023-07-05 15:05 UTC
Labels: schema, fda
