### ISSUE TITLE
Rule Editor not opening/selecting any other rule if already opened rule is not according to schema.

### ISSUE THREAD

**Issue by RamilCDISC** [cdisc-org/conformance-rules-editor#188] opened 2023-06-08 21:36 UTC
**Problem**
The rue editor does not select any other rule if an opened rule is not according to schema . Clicking multiple times or idle waiting also does not work. 

**Steps To Reproduce**
1. open rule editor
2. select any rule
3. in edit pane change to rule so it is not according to schema.
4. Now try selecting any other rule from the left rules pane

Following above steps you should be able to note that, selecting a new rule does not work anymore.

**Recommendations**
Rule Editor should notify the user when they try to select a new rule if the current rule has been edited without being saved or discarded.

**Comment by gerrycampion** [comment] 2023-06-28 16:54
Duplicate of https://github.com/cdisc-org/conformance-rules-editor/issues/132

**Closed by gerrycampion** 2023-06-28 16:54 UTC
Labels: enhancement
